import { makeStyles } from '@material-ui/core/styles';

const styles = makeStyles((theme) => ({
    gridRoot: {
        display: "flex",
        margin: "auto",
        justifyContent: "center",
        height: "1523px",
        width: "1304px",
        backgroundColor: "white",
        fontFamily: "Open Sans",
        maxHeight: '80vh',
        overflowY: 'scroll',
        [theme.breakpoints.down(1024)]: {
          width: "100%",
          position: "relative"
        },
    },
    productTitle: {
        width: "303px",
        height: "27px",
        flexGrow: "0",
        margin: "8px 11px 5px 0",
        fontSize: "20px",
        fontWeight: "600",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: "normal",
        letterSpacing: "normal",
        textAlign: "justify",
        color: "#000",
        [theme.breakpoints.down(1024)]: {
          position: "absolute",
          top: "35px",
          textAlign: "center",
          left: "50%",
          transform: "translateX(-50%)"
        },
    },
    imgGridContainer: {
      display: 'flex',
      [theme.breakpoints.down(1024)]: {
        flexDirection: "column-reverse"
      },
    },
    sideImgGrid: {
        flexDirection:"row",
        display: "flex",
        marginTop:"20px",
        [theme.breakpoints.down(1024)]: {
          flexDirection: "column",
        },
    },
    sideImgDiv: {
        flexDirection:"column",
        display: "flex",
        width:"100%",
        maxWidth: "65px",
        minWidth:"65px",
        justifyContent:"flex-end",
        alignItems:"flex-end",
        height:"413px",
        position:"relative",
        left:"60px",
        [theme.breakpoints.down(1024)]: {
          left: 0,
          flexDirection: "row",
          height: "auto",
          width: "100%",
          maxWidth: "none",
          justifyContent: "space-around",
          marginTop: "30px",
          alignItems: "center"
        },
    },
    sideImage: {
        width:"100%",
        maxWidth: "60px",
        minWidth:"60px",
        height:"%100",
        maxHeight: "60px",
        minHeight:"60px",
        marginBottom: "15px",
        border: "1px solid #bababa",
        borderRadius:"5px"
    },
    sellerPosts: {
      width: "212px",
      height: "22px",
      margin: "10.5px 23px 3px 8px",
      fontSize: "16px",
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      textAlign: "justify",
      color: "#323232",
  },
    subtotalPrice: {
        fontSize: "16px",
        lineHeight: "24px",
        textAlign: "right",
        color: "#323232"
    },
    subtotalPriceFiat: {
        color:"#BABABA",
        fontSize: "16px",
        lineHeight: "24px",
        textAlign: "right",
        marginLeft:"5px"
    },
    starsReputation: {
    width: "20px",
    height: "20px",
    marginRight: "5px",
    color: "#00ABD1",
  },
  opinions: {
    width: "130px",
    height: "19px",
    flexGrow: "0",
    margin: "-1px 40px 20px 13px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#bababa",
    textDecoration: "none !important",
  },
  Price: {
    fontSize: "20px",
    lineHeight: "27px",
    // textAlign: "right",
    color: "#323232",
    textDecoration: "none !important",
  },
  PriceFiat: {
    color:"#BABABA",
    fontSize: "20px",
    lineHeight: "27px",
    // textAlign: "right",
    marginLeft:"5px",
    textDecoration: "none !important",
  },
  Fee: {
    width: "242px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",
    textDecoration: "none !important",
  },
  color: {
    width: "112px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",
    textDecoration: "none !important",
  },
  stock: {
    width: "212px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#ab0707",
    textDecoration: "none !important",
    },  
  slidebuttonLeft: {
    color: "#00ABD1",
    textDecoration: "none",
    padding: "-10px",
    paddingLeft: "-10px",
    paddingRight: "1px",
    display: "inline-block",
    cursor: "pointer",
    position: "relative",
    top: '48px',
    marginTop: "5px",
    left: "-2.3rem",
    boxShadow: "0px 3px 6px #00000029",
    opacity: "1",
    width: "45px",
    height: "45px",
    textDecoration: "none",
    background: "#FFFFFF",
    borderRadius: "40px",
    //transform: "translateY(-50%)",

    "&:focus": {
      outline: "0",
    },
  },
  slidebuttonRight: {
    background: "#FFFFFF",
    color: "#00ABD1",
    textDecoration: "none",
    padding: "-10px",
    paddingRight: "-5px",
    //left: "0.7rem",
    display: "inline-block",
    cursor: "pointer",
    position: "relative",
    top: '45px',
    left: "-13px",
    marginTop: "5px",
    boxShadow: "0px 3px 6px #00000029",
    opacity: "1",
    width: "45px",
    height: "45px",
    textDecoration: "none",
    borderRadius: "40px",
    //transform: "translateY(-50%)",

    "&:focus": {
      outline: "0",
    },
  },
  delivery: {
    width: "100%",
    height: "19px",
    flexGrow: "0",
    margin: "3px 11px 5px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "left",
    color: "#00abd1",
    textDecoration: "none !important",
   },
   manageShipping: {
    width: "100%",
    height: "19px",
    flexGrow: "0",
    margin: "3px 11px 5px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#000",
    textDecoration: "none !important",
   },
   sizeRect: {
    width: "40px",
    height: "40px",
    flexGrow: "0",
    margin: "9px 4px 12px 6px",
    padding: "9px 13px 9px 12px",
    borderRadius: "5px",
    border: "solid 1px gray",
    textDecoration: "none !important",
    '&:hover, &:focus, &:active': {
      outline: 'none !important',
      border: "solid 1px #00abd1",
      cursor: "pointer",
    },
   },
   buy: {
    width: "29px",
    height: "19px",
    flexGrow: "0",
    margin: "17px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",
    textDecoration: "none !important",
   },
   available: {
    width: "99px",
    height: "19px",
    flexGrow: "0",
    margin: "17px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#bababa",
    textDecoration: "none !important",
   },
   btnBuyNow: {
    width: "237px",
    height: "32px",
    fontSize: "16px",
    textTransform: "none",
    flexGrow: "0",
    color: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    margin: "22px 0 1px 2px",
    padding: "4px 49px",
    borderRadius: "5px",
    backgroundColor: "#00abd1",
    '&:hover, &:focus, &:active': {
      outline: 'none !important',
    },
    '&:hover': {
      color: '#00ABD1',
      backgroundColor: 'White',
    },
   },
   btnAddCart: {
    width: "237px",
    height: "32px",
    fontSize: "16px",
    textTransform: "none",
    flexGrow: "0",
    color: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    margin: "22px 0 1px 2px",
    padding: "4px 49px",
    borderRadius: "5px",
    backgroundColor: "rgba(186, 186, 186, 0.5)",
    },
   mainImgNdSellDiv: {
    flexDirection:"column",
    display:"flex",
    justifyContent:"space-between",
    alignItems:"center",
    [theme.breakpoints.down(1024)]: {
      marginTop: "60px"
    },
  },
   mainImgDiv: {
	  display:"flex",
    flexDirection:"column",
   	justifyContent:"center",
    alignItems:"center",
    height:"-webkit-fill-available",
  },
   mainImg: {
    width:"100%",
    maxWidth: "500px",
    minWidth:"500px",
    height:"100%",
    maxHeight: "272px",
    minHeight:"272px",
    [theme.breakpoints.down(1024)]: {
      minWidth: 0,
    },
  },
   sellerGrid: {
    flexDirection:"column",
    display: "flex",
    [theme.breakpoints.down(1024)]: {
      display: "none",
    },
  },
   divider: {
    width:"100%",
    maxWidth: "710px",
    height: "1px",
    color: "rgba(186, 186, 186, 1)",
  },
  dividerFullWidth: {
    width:"100%",
    maxWidth: "1188px",
    height: "1px",
    color: "rgba(186, 186, 186, 1)",
    border: "1px solid #BABABA",
    marginTop: "69px"
  },
   sellTitleSpan: {
    flexDirection:"column",
    display: "flex"
  },
   mainSellerPostsDiv: {
    flexDirection:"row",
    display: "flex",
    widht:"100%",
    maxWidth: "850px",
    minWidth:"850px",
  },
  firstSellerPostsDiv: {
    flexDirection:"column",
    display: "flex",
    width:"100%",
    maxWidth: "180px",
    minWidth:"180px",
    height:"%100",
    maxHeight: "163px",
    minHeight:"163px",
    justifyContent:"center",
    alignItems:"center",
    border: "1px solid #bababa",
    borderRadius: "5px",
    marginRight: "20px",
    marginLeft: "-40px",
  },
  secondSellerPostsDiv: {
    flexDirection:"column",
    display: "flex",
    width:"100%",
    maxWidth: "180px",
    minWidth:"180px",
    height:"%100",
    maxHeight: "163px",
    minHeight:"163px",
    justifyContent:"center",
    alignItems:"center",
    border: "1px solid #bababa",
    borderRadius: "5px",
    marginRight: "20px"
  },
  thirdSellerPostsDiv: {
    flexDirection:"column",
    display: "flex",
    width:"100%",
    maxWidth: "180px",
    minWidth:"180px",
    height:"%100",
    maxHeight: "163px",
    minHeight:"163px",
    justifyContent:"center",
    alignItems:"center",
    border: "1px solid #bababa",
    borderRadius: "5px",
    marginRight: "20px"
  },
  fourthSellerPostsDiv: {
    flexDirection:"column",
    display: "flex",
    width:"100%",
    maxWidth: "180px",
    minWidth:"180px",
    height:"%100",
    maxHeight: "163px",
    minHeight:"163px",
    justifyContent:"center",
    alignItems:"center",
    border: "1px solid #bababa",
    borderRadius: "5px",

  },
  firstSellerImg: {
    width:"100%",
    maxWidth: "106px",
    minWidth:"106px",
    height:"%100",
    maxHeight: "60px",
    minHeight:"60px",
    marginBottom: "15px"
  },
  firstSellerSpanPrice: {
    flexDirection:"row",
    display: "flex"
  },
  secondSellerImg: {
    width:"100%",
    maxWidth: "106px",
    minWidth:"106px",
    height:"%100",
    maxHeight: "60px",
    minHeight:"60px",
    marginBottom: "15px"
  },
  secondSellerSpanPrice: {
    flexDirection:"row",
    display: "flex"
  },
  itemTitleDiv: {
    flexDirection:"column",
    display: "flex",
    width:"100%",
    maxWidth: "367px",
    minWidth:"367px",
    maxHeight: "610px",
    minHeight:"610px",
    justifyContent:"center",
    alignItems:"center",
    border:"1px solid #bababa",
    borderRadius:"5px",
    marginLeft:"-16px",
    [theme.breakpoints.down(1024)]: {
      maxWidth: "none",
      marginLeft: 0,
      marginTop: "30px",
      border: 0
    },
 },
 descriptionTitle: {
   fontSize: "20px",
   lineHeight: "27px",
 },
 backToShopIcon: {
    width: "17px",
    height: "23px",
    position: "relative",
    top: "-1px"
  },
  backToShopText: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#000000",
    '&:hover': {
      color: "#00ABD1",
      cursor: 'pointer',
      textDecoration: 'none',
    }
  },
}));

export default styles;    