import { makeStyles } from '@material-ui/core/styles';

const styles = makeStyles((theme) => ({
    gridRoot: {
        display: "flex",
        margin: "auto",
        justifyContent: "center",
        height: "1523px",
        width: "1304px",
        backgroundColor: "white",
        fontFamily: "Open Sans",
        maxHeight: '80vh',
        overflowY: 'scroll'
    },
    productTitle: {
        width: "303px",
        height: "27px",
        flexGrow: "0",
        margin: "8px 11px 5px 0",
        fontSize: "20px",
        fontWeight: "600",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: "normal",
        letterSpacing: "normal",
        textAlign: "justify",
        color: "#000",
    },
    sideImgGrid: {
        flexDirection:"row",
        display: "flex",
        marginTop:"20px"
    },
    sideImgDiv: {
        flexDirection:"column",
        display: "flex",
        width:"100%",
        maxWidth: "65px",
        minWidth:"65px",
        justifyContent:"center",
        alignItems:"center"
    },
    sideImage: {
        width:"100%",
        maxWidth: "60px",
        minWidth:"60px",
        height:"%100",
        maxHeight: "60px",
        minHeight:"60px",
        marginBottom: "15px",
        border: "1px solid #bababa",
        borderRadius:"5px"
    },
    sellerPosts: {
      width: "165px",
      height: "22px",
      margin: "10.5px 23px 3px 8px",
      fontSize: "16px",
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      textAlign: "justify",
      color: "#323232",
  },
    subtotalPrice: {
        fontSize: "16px",
        lineHeight: "24px",
        textAlign: "right",
        color: "#323232"
    },
    subtotalPriceFiat: {
        color:"#BABABA",
        fontSize: "16px",
        lineHeight: "24px",
        textAlign: "right",
        marginLeft:"5px"
    },
    starsReputation: {
    width: "20px",
    height: "20px",
    marginRight: "5px",
    color: "#00ABD1",
  },
  opinions: {
    width: "114px",
    height: "19px",
    flexGrow: "0",
    margin: "7px 42px 21px 13px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#bababa",
  },
  Price: {
    fontSize: "20px",
    lineHeight: "27px",
    // textAlign: "right",
    color: "#323232"
  },
  PriceFiat: {
    color:"#BABABA",
    fontSize: "20px",
    lineHeight: "27px",
    // textAlign: "right",
    marginLeft:"5px"
  },
  Fee: {
    width: "206px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",

  },
  color: {
    width: "112px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",
  },
  stock: {
    width: "204px",
    flexGrow: "0",
    margin:" 7px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#ab0707"
    },  
  slidebuttonLeft: {
    color: "#00ABD1",
    textDecoration: "none",
    padding: "-10px",
    paddingLeft: "-10px",
    paddingRight: "1px",
    display: "inline-block",
    cursor: "pointer",
    position: "relative",
    top: '48px',
    marginTop: "5px",
    left: "0.7rem",
    boxShadow: "0px 3px 6px #00000029",
    opacity: "1",
    width: "45px",
    height: "45px",
    textDecoration: "none",
    background: "#FFFFFF",
    borderRadius: "40px",
    //transform: "translateY(-50%)",

    "&:focus": {
      outline: "0",
    },
  },
  slidebuttonRight: {
    background: "#FFFFFF",
    color: "#00ABD1",
    textDecoration: "none",
    padding: "-10px",
    paddingRight: "-5px",
    //left: "0.7rem",
    display: "inline-block",
    cursor: "pointer",
    position: "relative",
    top: '45px',
    marginTop: "5px",
    boxShadow: "0px 3px 6px #00000029",
    opacity: "1",
    width: "45px",
    height: "45px",
    textDecoration: "none",
    borderRadius: "40px",
    //transform: "translateY(-50%)",

    "&:focus": {
      outline: "0",
    },
  },
  delivery: {
    width: "100%",
    height: "19px",
    flexGrow: "0",
    margin: "3px 11px 5px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "left",
    color: "#00abd1"
   },
   manageShipping: {
    width: "100%",
    height: "19px",
    flexGrow: "0",
    margin: "3px 11px 5px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#000"
   },
   sizeRect: {
    width: "40px",
    height: "40px",
    flexGrow: "0",
    margin: "9px 4px 12px 6px",
    padding: "9px 13px 9px 12px",
    borderRadius: "5px",
    border: "solid 1px gray",
    '&:hover, &:focus, &:active': {
      outline: 'none !important',
      border: "solid 1px #00abd1",
      cursor: "pointer",
    },
   },
   buy: {
    width: "29px",
    height: "19px",
    flexGrow: "0",
    margin: "17px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#323232",
   },
   available: {
    width: "78px",
    height: "19px",
    flexGrow: "0",
    margin: "17px 7px 4px 7px",
    fontSize: "14px",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: "normal",
    letterSpacing: "normal",
    textAlign: "justify",
    color: "#bababa",
   },
   btnBuyNow: {
    width: "206px",
    height: "32px",
    fontSize: "16px",
    textTransform: "none",
    flexGrow: "0",
    color: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    margin: "22px 0 1px 2px",
    padding: "4px 49px",
    borderRadius: "5px",
    backgroundColor: "#00abd1",
    '&:hover, &:focus, &:active': {
      outline: 'none !important',
    },
    '&:hover': {
      color: '#00ABD1',
      backgroundColor: 'White',
    },
    },
    btnAddCart: {
    width: "206px",
    height: "32px",
    fontSize: "16px",
    textTransform: "none",
    flexGrow: "0",
    color: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    margin: "22px 0 1px 2px",
    padding: "4px 49px",
    borderRadius: "5px",
    backgroundColor: "rgba(186, 186, 186, 0.5)",
    // '&:hover, &:focus, &:active': {
    //   outline: 'none !important',
    // },
    // '&:hover': {
    //   color: 'white',
    //   backgroundColor: '#00ABD1',
    // },
    },            
}));

export default styles;    